/**
 * Generate Lucide-style React components from icons category SVG folders.
 *
 *   node scripts/build-react.mjs
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "node-html-parser";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.join(__dirname, "..");
const ICONS_ROOT = path.join(REPO_ROOT, "icons");
const OUT_DIR = path.join(REPO_ROOT, "react", "src", "icons");
const PACK_IDS = ["ingredients", "utensils", "dishes", "beverages"];

const VIEWBOX_DEFAULT = "0 0 2048 2048";

function pascalCaseFromFile(filename) {
  const base = path.basename(filename, ".svg");
  const parts = base.split("_").filter(Boolean).map((part) => {
    if (/^\d/.test(part)) return part;
    return part.charAt(0).toUpperCase() + part.slice(1);
  });
  let name = parts.join("");
  if (!name || /^\d/.test(name)) name = `Icon${name}`;
  return name;
}

function categoryPrefix(packId) {
  return packId.charAt(0).toUpperCase() + packId.slice(1);
}

function collectIcons() {
  const byBasename = new Map();

  for (const packId of PACK_IDS) {
    const svgDir = path.join(ICONS_ROOT, packId, "svg");
    if (!fs.existsSync(svgDir)) {
      console.error(`Missing ${svgDir}`);
      process.exit(1);
    }
    for (const file of fs.readdirSync(svgDir).filter((f) => f.endsWith(".svg"))) {
      const list = byBasename.get(file) ?? [];
      list.push({ packId, file, absPath: path.join(svgDir, file) });
      byBasename.set(file, list);
    }
  }

  const entries = [];
  for (const [, list] of byBasename) {
    const dup = list.length > 1;
    for (const item of list) {
      const simple = pascalCaseFromFile(item.file);
      const exportName = dup
        ? `${categoryPrefix(item.packId)}${simple}`
        : simple;
      entries.push({ ...item, exportName });
    }
  }

  entries.sort((a, b) => a.exportName.localeCompare(b.exportName, "en"));
  return entries;
}

function parseSvg(absPath) {
  const raw = fs.readFileSync(absPath, "utf8");
  const doc = parse(raw, { lowerCaseTagName: false });
  const svg = doc.querySelector("svg");
  const viewBox =
    svg?.getAttribute("viewBox")?.trim() || VIEWBOX_DEFAULT;

  const nodes = [];
  for (const el of doc.querySelectorAll("path, circle, rect, ellipse, line, polyline, polygon")) {
    const tag = el.tagName.toLowerCase();
    const attrs = {};
    for (const [key, value] of Object.entries(el.attributes)) {
      if (key === "fill" && value !== "none") continue;
      if (key === "style" || key === "class") continue;
      attrs[key] = value;
    }
    if (tag === "path" && !attrs.d) continue;
    nodes.push([tag, attrs]);
  }

  if (nodes.length === 0) {
    console.error(`No shapes in ${absPath}`);
    process.exit(1);
  }

  return { viewBox, nodes };
}

function serializeNodes(nodes) {
  const lines = nodes.map(([tag, attrs]) => {
    const inner = Object.entries(attrs)
      .map(([k, v]) => `${k}: ${JSON.stringify(v)}`)
      .join(", ");
    return `    ["${tag}", { ${inner} }],`;
  });
  return lines.join("\n");
}

function writeIconFile(entry, viewBox, nodes) {
  const fileName = `${entry.exportName}.tsx`;
  const body = `import { createFoodIcon } from "../createFoodIcon.js";

export const ${entry.exportName} = createFoodIcon(
  "${entry.exportName}",
  ${JSON.stringify(viewBox)},
  [
${serializeNodes(nodes)}
  ],
);
`;
  fs.writeFileSync(path.join(OUT_DIR, fileName), body);
  return fileName;
}

function main() {
  fs.rmSync(OUT_DIR, { recursive: true, force: true });
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const entries = collectIcons();
  const exportLines = [];

  for (const entry of entries) {
    const { viewBox, nodes } = parseSvg(entry.absPath);
    writeIconFile(entry, viewBox, nodes);
    exportLines.push(
      `export { ${entry.exportName} } from "./icons/${entry.exportName}.js";`,
    );
  }

  const indexPath = path.join(REPO_ROOT, "react", "src", "index.ts");
  fs.writeFileSync(
    indexPath,
    `/** Generated by scripts/build-react.mjs — do not edit */\n\nexport type { FoodIconProps, IconNode } from "./createFoodIcon.js";\nexport { createFoodIcon } from "./createFoodIcon.js";\n\n${exportLines.join("\n")}\n`,
  );

  console.log(`Generated ${entries.length} React icons in react/src/icons/`);
}

main();
